---
title: "Julius Kricheldorff"
output:
  distill::distill_article:
    css: styles2.css
---

## Contact Information

- Email: julius@kricheldorff.de


## Education

### PhD Student Cognitive Neuroscience, Carl von Ossietzky University

- Date: March 2019 - Present
- Dissertation: "Decision-making deficits in Parkinson's disease"
- Advisor: Prof. Dr. med. K. Witt

### Master of Science in Behavioural and Cognitive Neuroscience, University of Groningen

- Date: September 2016 - August 2018

### Bachelor of Science in Psychology, University of Groningen

- Date: September 2012 - August 2016

## Work Experience

### Research Assistant, Carl von Ossietzky University

- Date: June 2019 - Present
- Responsibilities:
  - Designed, implemented and recorded behavioural- and EEG experiments 
  - Acquisition, planning and running the EEG research lab
  - Mentored and supervision of medical students on best practices for scientific research 
  
## Skills

- Programming languages: Python, R, MATLAB
- Analysis software: SPSS, JASP
- Experimental Software: Psychopy, Opensesame, Psychtoolbox
- Neuroimaging: Electroencephalography
- Imaging software: Fieldtrip, EEGLAB
- Statistical modeling: GLM, mixed-effects modeling, Bayesian regression modeling, drift-diffusion modeling
- Version control: Git, GitHub
- Data visualization: ggplot2, seaborn

