---
title: CV
name: Julius
surname: Kricheldorff
position: "PhD-Student"
address: "Carl von Ossietzky Universität, Fakultät VI, Neurology"
www: julius-kricheldorff.com
email: "julius@kricheldorff.de"
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "PhD-Student interested in decision-making, Parkinson's disease and statistical modelling"
output: 
  vitae::markdowncv:
    theme: kjhealy
    
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

## Employment
```{r}
library(tibble)
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

## Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Groningen, Netherlands",
  "BSc. Psychology", "2012-2016", "University of Groningen", "Groningen, Netherlands",
  "MSc. Behavioral and Cognitive Neuroscience", "2016-2018", "University of Groningen", "Groningen, Netherlands"
) %>% 
  detailed_entries(Institution, Year, Where, Degree)
```



## Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

